name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.12"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v3

      - name: Install Python
        run: uv python install ${{ matrix.python-version }}

      - name: Install dependencies
        run: uv pip install --system '.[dev]'

      - name: Ruff
        run: ruff check .

      - name: Black
        run: black --check .

      - name: MyPy
        run: mypy src

      - name: Pytest
        run: pytest -q

